### ISSUE TITLE
Ueditor upload不工作

### ISSUE THREAD

**Issue by lear2012** [qloog/laravel5-backend#9]
有没有配置可以参考一下啊 ：）
http://local.com/admin/upload/image?action=config&&noCache=1487753686177
返回正确json，但是
总报errorHandler is not defined

**Comment by qloog** [comment]
@lear2012  默认不需要配置errorHandler， 可以把错误信息发上来看看。

**Comment by lear2012** [comment]
已经解决了，谢谢啊

**Comment by qloog** [comment]
👍
